# Generated by Django 3.1.4 on 2021-09-07 10:57

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_evidencefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencefile',
            name='file',
            field=models.FileField(upload_to=report.models.get_report_public_id),
        ),
    ]
