# Generated by Django 3.1.4 on 2021-09-07 17:13

from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210907_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencefile',
            name='file',
            field=models.FileField(max_length=500, upload_to=report.models.get_report_public_id),
        ),
    ]
