from django.core.management.base import BaseCommand
from django.db import transaction

from countries.models import Country


class Command(BaseCommand):
    help = "import countries"

    def handle(self, *args, **kwargs):
        with transaction.atomic():
            lines = [
                ("AF", "Afghanistan"),
                ("AL", "Albania"),
                ("DZ", "Algeria"),
                ("AS", "American Samoa"),
                ("AO", "Angola"),
                ("AG", "Antigua and Barbuda"),
                ("AR", "Argentina"),
                ("AM", "Armenia"),
                ("AU", "Australia"),
                ("AT", "Austria"),
                ("AZ", "Azerbaijan"),
                ("BS", "Bahamas, The"),
                ("BH", "Bahrain"),
                ("BD", "Bangladesh"),
                ("BB", "Barbados"),
                ("BY", "Belarus"),
                ("BE", "Belgium"),
                ("BZ", "Belize"),
                ("BJ", "Benin"),
                ("BT", "Bhutan"),
                ("BO", "Bolivia"),
                ("BA", "Bosnia and Herzegovina"),
                ("BW", "Botswana"),
                ("BR", "Brazil"),
                ("BN", "Brunei Darussalam"),
                ("BG", "Bulgaria"),
                ("BF", "Burkina Faso"),
                ("KH", "Cambodia"),
                ("CM", "Cameroon"),
                ("CA", "Canada"),
                ("CF", "Central African Republic"),
                ("TD", "Chad"),
                ("CL", "Chile"),
                ("CN", "China"),
                ("CO", "Colombia"),
                ("KM", "Comoros"),
                ("CD", "Congo, Dem. Rep."),
                ("CG", "Congo, Rep."),
                ("CR", "Costa Rica"),
                ("CI", "Côte d'Ivoire"),
                ("HR", "Croatia"),
                ("CU", "Cuba"),
                ("CY", "Cyprus"),
                ("CZ", "Czech Republic"),
                ("DK", "Denmark"),
                ("DJ", "Djibouti"),
                ("DM", "Dominica"),
                ("DO", "Dominican Republic"),
                ("EC", "Ecuador"),
                ("EG", "Egypt, Arab Rep."),
                ("SV", "El Salvador"),
                ("GQ", "Equatorial Guinea"),
                ("ER", "Eritrea"),
                ("EE", "Estonia"),
                ("ET", "Ethiopia"),
                ("FJ", "Fiji"),
                ("FI", "Finland"),
                ("FR", "France"),
                ("GA", "Gabon"),
                ("GM", "Gambia, The"),
                ("GE", "Georgia"),
                ("DE", "Germany"),
                ("GH", "Ghana"),
                ("GR", "Greece"),
                ("GD", "Grenada"),
                ("GT", "Guatemala"),
                ("GN", "Guinea"),
                ("GW", "Guinea-Bissau"),
                ("GY", "Guyana"),
                ("HT", "Haiti"),
                ("HN", "Honduras"),
                ("HU", "Hungary"),
                ("IS", "Iceland"),
                ("IN", "India"),
                ("ID", "Indonesia"),
                ("IR", "Iran, Islamic Rep."),
                ("IQ", "Iraq"),
                ("IE", "Ireland"),
                ("IL", "Israel"),
                ("IT", "Italy"),
                ("JM", "Jamaica"),
                ("JP", "Japan"),
                ("JO", "Jordan"),
                ("KZ", "Kazakhstan"),
                ("KE", "Kenya"),
                ("KI", "Kiribati"),
                ("KR", "Korea, Rep."),
                ("KW", "Kuwait"),
                ("KG", "Kyrgyz Republic"),
                ("LA", "Lao PDR"),
                ("LV", "Latvia"),
                ("LB", "Lebanon"),
                ("LS", "Lesotho"),
                ("LR", "Liberia"),
                ("LY", "Libya"),
                ("LT", "Lithuania"),
                ("LU", "Luxembourg"),
                ("MK", "Macedonia (North)"),
                ("MG", "Madagascar"),
                ("MW", "Malawi"),
                ("MY", "Malaysia"),
                ("MV", "Maldives"),
                ("ML", "Mali"),
                ("MT", "Malta"),
                ("MR", "Mauritania"),
                ("MU", "Mauritius"),
                ("MX", "Mexico"),
                ("FM", "Micronesia, Fed. Sts."),
                ("MD", "Moldova"),
                ("MN", "Mongolia"),
                ("ME", "Montenegro"),
                ("MA", "Morocco"),
                ("MZ", "Mozambique"),
                ("MM", "Myanmar"),
                ("NA", "Namibia"),
                ("NP", "Nepal"),
                ("NL", "Netherlands"),
                ("NZ", "New Zealand"),
                ("NI", "Nicaragua"),
                ("NE", "Niger"),
                ("NG", "Nigeria"),
                ("NO", "Norway"),
                ("OM", "Oman"),
                ("PK", "Pakistan"),
                ("PA", "Panama"),
                ("PG", "Papua New Guinea"),
                ("PY", "Paraguay"),
                ("PE", "Peru"),
                ("PH", "Philippines"),
                ("PL", "Poland"),
                ("PT", "Portugal"),
                ("QA", "Qatar"),
                ("RO", "Romania"),
                ("RU", "Russian Federation"),
                ("RW", "Rwanda"),
                ("WS", "Samoa"),
                ("ST", "São Tomé and Principe"),
                ("SA", "Saudi Arabia"),
                ("SN", "Senegal"),
                ("RS", "Serbia"),
                ("SC", "Seychelles"),
                ("SL", "Sierra Leone"),
                ("SG", "Singapore"),
                (
                    "SK",
                    "Slovak Republic",
                ),
                ("SI", "Slovenia"),
                ("SB", "Solomon Islands"),
                ("ZA", "South Africa"),
                ("SS", "South Sudan"),
                ("ES", "Spain"),
                ("LK", "Sri Lanka"),
                ("SD", "Sudan"),
                ("SR", "Suriname"),
                ("SZ", "Eswatini (Swaziland)"),
                ("SE", "Sweden"),
                ("CH", "Switzerland"),
                ("TJ", "Tajikistan"),
                ("TZ", "Tanzania"),
                ("TH", "Thailand"),
                ("TL", "Timor-Leste"),
                ("TG", "Togo"),
                ("TO", "Tonga"),
                ("TT", "Trinidad and Tobago"),
                ("TN", "Tunisia"),
                ("TR", "Turkey"),
                ("TM", "Turkmenistan"),
                ("UG", "Uganda"),
                ("UA", "Ukraine"),
                ("AE", "United Arab Emirates"),
                ("GB", "United Kingdom"),
                ("US", "United States"),
                ("UY", "Uruguay"),
                ("VE", "Venezuela, RB"),
                ("ZM", "Zambia"),
                ("ZW", "Zimbabwe"),
            ]

            for line in lines:

                country = Country.objects.filter(iso_code=line[0]).first()
                if not country:
                    country = Country()
                    country.iso_code = line[0]
                country.name = line[1]

                country.save()
